name: debug_ray_memory
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch=1.11.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - ray[rllib,defaults]==1.12.1
    - hydra-core
    - tensorboard
